services:
  - type: web
    name: friend-of-global-economy
    env: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT public/
    envVars:
      - key: APP_ENV
        value: production 