CREATE TABLE IF NOT EXISTS tweets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL,
    created_at DATETIME NOT NULL,
    twitter_id TEXT UNIQUE,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
); 